### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [CaptivatedLLC/official-gtm-tag#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) encodeUriComponent should be used on user provided values that are then used as parameters in your url. These methods take in a single text argument and return a URI Encoded string. You should use this method on data.widget_id when generating the url
const url = 'https://api.captivated.works/widget.js?id=' + data.widget_id;

**Comment by christophersansone** [comment]
@praveena-pappu Thanks for the feedback!  I created #3 to address the issue, then merged and updated `metadata.yaml`.  How does it look now?
